name: Reusable workflow
on:
  workflow_call:
    inputs:
      who-to-greet:
        description: 'OscarLSCA'
        type: string
        required: true
        default: Worldjobs:
jobs:  
  reusable-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greet someone
        run: echo "Hello ${{ inputs.who-to-greet }}"
